{
 "title": "Stroy Node Dashboard",
 "description": "This dashboard provides a comprehensive view of key metrics from Story Protocol node. It offers insights into node performance, health and activity.",
 "tags": [
  "cometbft",
  "geth"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(cometbft_p2p_peers,instance)"
    }
   },
   {
    "name": "chain_id",
    "query": {
     "query": "label_values(cometbft_p2p_peers,chain_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n    <br>\n    <img src=\"https://services.kjnodes.com/assets/images/logos/story.png\"><br><br>\n    <h1>Story Consensus and Execution Node Metrics</h1>\n    <h5>⚡️ Powered by <a href=\"https://kjnodes.com\">kjnodes</a></h5>\n</div>"
   }
  },
  { "title": "kjnodes Story Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/testnet/story/\" target=\"_blank\">Story Services</a></h1>\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/testnet/story/installation/\" target=\"_blank\">Node Installation</a></h1>\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/testnet/story/upgrade/\" target=\"_blank\">Node Upgrade</a></h1>\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/testnet/story/state-sync/\" target=\"_blank\">State-Sync</a></h1>\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/testnet/story/snapshot/\" target=\"_blank\">Snapshot</a></h1>\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/testnet/story/snapshot-archive/\" target=\"_blank\">Snapshot (Archive)</a></h1>\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/testnet/story/useful-commands/\" target=\"_blank\">Useful Commands</a></h1>\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/testnet/story/public-rpc/\" target=\"_blank\">RPC Scanner</a></h1>\r\n</div>"
   }
  },
  { "title": "Story Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "options": {
    "content": "# Cometbft Node Metrics\n\n*Metrics collected from a Story Cometbft Prometheus endpoint.*\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h2>System</h2>\r\n</div>"
   }
  },
  {
   "title": "Story Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "lib_buildinfo_version{instance=\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"$instance\", job=\"cometbft\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncing",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_blocksync_syncing{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Block Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_latest_block_height{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cometbft_consensus_latest_block_height{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\", job=\"cometbft\"}[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\", job=\"cometbft\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$instance\", job=\"cometbft\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$instance\", job=\"cometbft\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h2>Network</h2>\r\n</div>"
   }
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 2, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Peer Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(cometbft_p2p_peer_receive_bytes_total{instance=\"$instance\", chain_id=\"$chain_id\"}[1m]))",
     "legendFormat": "inbound"
    },
    {
     "expr": "sum(rate(cometbft_p2p_peer_send_bytes_total{instance=\"$instance\", chain_id=\"$chain_id\"}[1m]))",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 34 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h2>Blockchain</h2>\r\n</div>"
   }
  },
  {
   "title": "Block time",
   "type": "stat",
   "description": "Number of blocks produced last minute",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "60 / round(increase(cometbft_consensus_height{instance=\"$instance\", chain_id=\"$chain_id\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "stat",
   "description": "Number of blocks produced last minute",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(cometbft_consensus_height{instance=\"$instance\", chain_id=\"$chain_id\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "timeseries",
   "description": "Number of blocks produced last minute",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "increase(cometbft_consensus_height{instance=\"$instance\", chain_id=\"$chain_id\"}[1m])",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Consensus Block Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{instance=\"$instance\", chain_id=\"$chain_id\"} - cometbft_consensus_missing_validators{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Confirmed Tx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_size_bytes{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cometbft_mempool_size_bytes{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Online: bonded tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline: bonded tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators_power{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline: Voting Power %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators_power{instance=\"$instance\", chain_id=\"$chain_id\"} / cometbft_consensus_validators_power{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unconfirmed Tx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_size{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Geth Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 53 },
   "options": {
    "content": "# Geth Node Metrics\n\n*Metrics collected from a Story Geth Prometheus endpoint.*\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 56 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h2>System</h2>\r\n</div>"
   }
  },
  {
   "title": "Geth Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "geth_info{instance=\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(system_cpu_sysload{instance=\"$instance\"}[1m])",
     "legendFormat": "system"
    },
    {
     "expr": "rate(system_cpu_syswait{instance=\"$instance\"}[1m])",
     "legendFormat": "iowait"
    },
    {
     "expr": "rate(system_cpu_procload{instance=\"$instance\"}[1m])",
     "legendFormat": "geth"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(system_memory_allocs{instance=\"$instance\"}[1m])",
     "legendFormat": "alloc"
    },
    {
     "expr": "system_memory_used{instance=\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "system_memory_held{instance=\"$instance\"}",
     "legendFormat": "held"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(system_disk_readbytes{instance=\"$instance\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(system_disk_writebytes{instance=\"$instance\"}[1m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 66 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h2>Network</h2>\r\n</div>"
   }
  },
  {
   "title": "P2P Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_peers{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 2, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "p2p_peers{instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Peer Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(p2p_ingress{instance=\"$instance\"}[5m])",
     "legendFormat": "ingress"
    },
    {
     "expr": "rate(p2p_egress{instance=\"$instance\"}[5m])",
     "legendFormat": "egress"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 76 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h2>Blockchain</h2>\r\n</div>"
   }
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 2, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "chain_head_block{instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Transaction Pool",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_pending{instance=\"$instance\"}",
     "legendFormat": "executable"
    },
    {
     "expr": "txpool_queued{instance=\"$instance\"}",
     "legendFormat": "gapped"
    },
    {
     "expr": "txpool_local{instance=\"$instance\"}",
     "legendFormat": "local"
    }
   ]
  },
  {
   "title": "Transaction Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "txpool_pending{instance=\"$instance\"}",
     "legendFormat": "executable"
    },
    {
     "expr": "txpool_queued{instance=\"$instance\"}",
     "legendFormat": "gapped"
    },
    {
     "expr": "txpool_local{instance=\"$instance\"}",
     "legendFormat": "local"
    }
   ]
  },
  {
   "title": "Block processing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "chain_execution{quantile=\"0.9999\", instance=\"$instance\"}",
     "legendFormat": "execution (q=0.9999)"
    },
    {
     "expr": "chain_validation{quantile=\"0.9999\", instance=\"$instance\"}",
     "legendFormat": "validation (q=0.9999)"
    },
    {
     "expr": "chain_write{quantile=\"0.9999\", instance=\"$instance\"}",
     "legendFormat": "commit (q=0.9999)"
    },
    {
     "expr": "chain_account_reads{quantile=\"0.9999\", instance=\"$instance\"}",
     "legendFormat": "account read (q=0.9999)"
    },
    {
     "expr": "chain_account_updates{quantile=\"0.9999\", instance=\"$instance\"}",
     "legendFormat": "account update (q=0.9999)"
    },
    {
     "expr": "chain_account_hashes{quantile=\"0.9999\", instance=\"$instance\"}",
     "legendFormat": "account hash (q=0.9999)"
    },
    {
     "expr": "chain_account_commits{quantile=\"0.9999\", instance=\"$instance\"}",
     "legendFormat": "account commit (q=0.9999)"
    },
    {
     "expr": "chain_storage_reads{quantile=\"0.9999\", instance=\"$instance\"}",
     "legendFormat": "storage read (q=0.9999)"
    },
    {
     "expr": "chain_storage_updates{quantile=\"0.9999\", instance=\"$instance\"}",
     "legendFormat": "storage update (q=0.9999)"
    },
    {
     "expr": "chain_storage_commits{quantile=\"0.9999\", instance=\"$instance\"}",
     "legendFormat": "storage commit (q=0.9999)"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(txpool_valid{instance=\"$instance\"}[1m])",
     "legendFormat": "valid"
    },
    {
     "expr": "rate(txpool_invalid{instance=\"$instance\"}[1m])",
     "legendFormat": "invalid"
    },
    {
     "expr": "rate(txpool_underpriced{instance=\"$instance\"}[1m])",
     "legendFormat": "underpriced"
    },
    {
     "expr": "rate(txpool_pending_discard{instance=\"$instance\"}[1m])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(txpool_pending_replace{instance=\"$instance\"}[1m])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(txpool_pending_ratelimit{instance=\"$instance\"}[1m])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(txpool_pending_nofunds{instance=\"$instance\"}[1m])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(txpool_queued_discard{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(txpool_queued_replace{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(txpool_queued_ratelimit{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(txpool_queued_nofunds{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped nofunds"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 104 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h2>Database</h2>\r\n</div>"
   }
  },
  {
   "title": "Data rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(eth_db_chaindata_disk_read{instance=\"$instance\"}[1m])",
     "legendFormat": "leveldb read"
    },
    {
     "expr": "rate(eth_db_chaindata_disk_write{instance=\"$instance\"}[1m])",
     "legendFormat": "leveldb write"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_read{instance=\"$instance\"}[1m])",
     "legendFormat": "ancient read"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_write{instance=\"$instance\"}[1m])",
     "legendFormat": "ancient write"
    }
   ]
  },
  {
   "title": "Storage size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_size{instance=\"$instance\"}",
     "legendFormat": "leveldb"
    },
    {
     "expr": "eth_db_chaindata_ancient_size{instance=\"$instance\"}",
     "legendFormat": "ancient"
    }
   ]
  }
 ]
}